spring:
  sql:
    init:
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/fantasy_bd
    username:
    password:

server:
  port: 8081
  servlet:
    context-path: /api/v1
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
