create table IF NOT EXISTS TEAM
(
    id   integer generated by default as identity primary key,
    name varchar not null unique
);

create table IF NOT EXISTS PLAYER
(
    id          int generated by default as identity,
    team_id     integer references TEAM (id),
    nickname    varchar not null,
    stat        smallint check ( stat > 0 ) check ( stat < 101 ),
    price       smallint check (price > 0),
    first_name  varchar,
    second_name varchar,
    role        varchar,
    primary key (id)
);

create table IF NOT EXISTS TOURNAMENT
(
    id         integer primary key generated by default as identity,
    name       varchar not null,
    start_time date,
    is_started boolean default false,
    prize_pool integer,
    is_ended   bool    default false
);

create table if not exists match
(
    id            int primary key generated by default as identity,
    first_team    int references TEAM (id) on delete set null,
    second_team   int references TEAM (id) on delete set null,
    tournament_id int references tournament (id) on delete set null,
    start_time    date,
    is_started    boolean default false,
    is_ended      boolean default false,
    score         varchar
);
-- ALTER TABLE match
--     add CONSTRAINT  not_the_same_teams_in_match check ( match.first_team != match.second_team );
--
-- ALTER TABLE match
--     add column match_winner int
--         references team (id)
--         check ( match_winner = match.first_team OR match_winner = match.second_team);
create table if not exists map
(
    id   smallint primary key generated by default as identity,
    name varchar unique
);

create table if not exists match_map
(
    match_id integer references MATCH (id),
    map_id   integer references map (id)
);

create table if not exists match_player_stat
(
    match_id     int references match (id),
    player_id    int references PLAYER (id),
    primary key (match_id, player_id),
    frags        smallint,
    death        smallint,
    assist       smallint,
    flash_assist smallint,
    adr          decimal,
    rating       decimal,
    duels_won    smallint,
    kd_diff      smallint
);

create table if not exists role
(
    id   smallint generated by default as identity primary key,
    name varchar not null
);

create table if not exists usr
(
    id          bigint primary key generated by default as identity,
    nickname    varchar unique not null,
    email       varchar unique,
    first_name  varchar,
    second_name varchar,
    avatar      varchar,
    birth_day   date,
    active      boolean
);

create table if not exists user_role
(
    user_id integer references usr (id),
    role_id smallint references role (id),
    primary key (user_id, role_id)
);